version: 2
updates:
  - package-ecosystem: github-actions
    target-branch: development
    directory: /
    schedule:
      interval: weekly
      day: sunday
    cooldown:
      default-days: 7
    commit-message:
      prefix: deps

  - package-ecosystem: npm
    target-branch: development
    directory: /
    schedule:
      interval: weekly
      day: sunday
    cooldown:
      default-days: 7
    commit-message:
      prefix: deps
