name: 🔨 Build and Push Docker Image

on:
  pull_request:
  push:
    branches: [development]
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for the Docker image"
        type: string
        required: true
  workflow_call:
    inputs:
      tag:
        description: "Tag for the Docker image"
        type: string
        required: true
    secrets:
      DOCKER_PASSWORD:
        required: true
      GARGE_PAT:
        required: false

permissions:
  contents: read

jobs:
  dev:
    if: github.ref == 'refs/heads/development'
    uses: equinor/ops-actions/.github/workflows/docker.yml@e925ef9959a37d43073b77efa2f73c64253fbd55 # v9.37.2
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    with:
      build_args: '{"NEXT_PUBLIC_API_URL":"https://garge-api-dev.prod.tumogroup.com/api"}'
      environment: dev
      registry: registry.hub.docker.com
      username: sondresjo
      repository: sondresjo/garge-app
      tag: dev
      tag_latest: false

  prod:
    if: inputs.tag != ''
    uses: equinor/ops-actions/.github/workflows/docker.yml@e925ef9959a37d43073b77efa2f73c64253fbd55 # v9.37.2
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    with:
      build_args: '{"NEXT_PUBLIC_API_URL":"https://garge-api.prod.tumogroup.com/api"}'
      environment: prod
      registry: registry.hub.docker.com
      username: sondresjo
      repository: sondresjo/garge-app
      tag: ${{ inputs.tag }}
      tag_latest: true

  update-chart:
    needs: prod
    if: inputs.tag != ''
    uses: sondresjolyst/garge/.github/workflows/update-chart.yml@main
    secrets:
      GARGE_PAT: ${{ secrets.GARGE_PAT }}
    with:
      chart_name: garge-app
      tag: ${{ inputs.tag }}
