name: Build and Push Docker Image

on:
  push:
    branches:
      - development
      - main
    tags:
      - '*'

jobs:
  dev:
    if: github.ref == 'refs/heads/development'
    uses: equinor/ops-actions/.github/workflows/docker.yml@20648f341aa77c794bae98da077409faf00652a1
    secrets:
        password: ${{ secrets.DOCKER_PASSWORD }}
    with:
      environment: dev
      registry: ${{ vars.DOCKER_USERNAME }}
      username: ${{ vars.DOCKER_USERNAME }}
      tag: dev

  prod:
    if: github.ref == 'refs/heads/main' && startsWith(github.ref, 'refs/tags/')
    uses: equinor/ops-actions/.github/workflows/docker.yml@20648f341aa77c794bae98da077409faf00652a1
    secrets:
        password: ${{ secrets.DOCKER_PASSWORD }}
    with:
      environment: prod
      registry: ${{ vars.DOCKER_USERNAME }}
      username: ${{ vars.DOCKER_USERNAME }}
      tag: ${{ github.ref_name }}