name: 🚀 Create release

on:
  push:
    branches:
      - main

permissions:
  contents: write # Required to update changelog file
  pull-requests: write # Required to create release PRs

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-24.04
    steps:
      - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38
        with:
          release-type: node
